version: '3.4'

services:
  auctiondb:
    container_name: auctiondb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auctionviewdb:
    container_name: auctionviewdb
    environment:
      - SA_PASSWORD=Admin1234
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  auction.api:
    container_name: auction.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings__ConnectionString=mongodb://auctiondb:27017"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8000:80"
    depends_on:
      - auctiondb
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  auction.view.api:
    container_name: auction.view.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings__ConnectionString=Server=auctionviewdb;Database=ProductDb;User Id=sa;Password=Admin1234;"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:80"
    depends_on:
      - auctionviewdb
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
